package ort.da.obligatorio339182.model.domain.usuarios;

public enum Permiso {
	ADMIN_DASHBOARD, 
	PROPIETARIO_DASHBOARD,
	BORRAR_NOTIFICACIONES,
	EMULAR_TRANSITO,
	ASIGNAR_BONIFICACION,
	BUSCAR_PROPIETARIO,
	CAMBIAR_ESTADO_PROPIETARIO
}
